module.exports = function() {
    console.log("");
    console.log("[ Programa ]");
    console.log("    xass | Edición rápida de ficheros *.ass (SubStation Alpha)");
    console.log("[ Uso ]");
    console.log("    $ xass <ficheros> -x <comando>");
    console.log("    $ xass <ficheros> -x <comando> -a [arg] -b [arg] -c [arg]");
    console.log("[ Comando ]");
    console.log("    · xass -x interfaz: interfaz gráfica (con servidor y navegador)");
    console.log("    · xass -x separar: aplica una separación temporal mínima entre subtítulos");
    console.log("      --separacion: por defecto «0.17»");
    console.log("      --incluir-estilo: solo modificará los estilos coincidentes (en texto o expresión regular)");
    console.log("      --excluir-estilo: solo modificará los estilos no coincidentes (en texto o expresión regular)");
    console.log("      --carga-izquierda: parte de la separación del subtítulo solapado anterior (en %)");
    console.log("      --carga-derecha: parte de la separación del subtítulo solapado posterior (en %)");
    console.log("    · xass -x ayuda: imprime esta ayuda");
    console.log("    · xass -x version: imprime la versión actual del xass en ejecución");
    console.log("[ Documentación ]");
    console.log("    https://github.com/allnulled/xass");
    console.log("");
    console.log("");
    console.log("");
    console.log("");
    console.log("");
    console.log("");
    console.log("");
    console.log("");
};